name: startMagent2DevEC2
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start AWS EC2
        run: |
          aws ec2 start-instances --instance-ids ${{secrets.AWS_EC2_INSTANCE_ID }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      - name: update ec2 instance
        run: sudo apt update -y
      - name: install docker-compose
        run: sudo apt install docker-compose -y
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: pull docker image
        run: docker pull noizebomb/springboot-app-2:0.0.1
      - name: pull docker-compose file
        run: wget https://github.com/Noizebomb/webapp-docker-build/blob/main/docker-compose.yml
      - name: run docker-compose
        run: docker run -p 8080:8080 -d noizebomb/springboot-app-2:0.0.1
